# Generated by Django 3.0.5 on 2020-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
